version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - QA_POSTGRES_DATABASE_URL=postgresql://postgres:leibushor@db:5433/qa_flask_app_db     
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leibushor
      POSTGRES_DB: qa_flask_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
